services:
  dajango_app:
    build:
    context: .
    dockerfile: Dockerfile
    args:
      # Use user id & group id in .env
      USER_ID: ${USER_ID:-0}
      GROUP_ID: ${GROUP_ID:-0}
    user: ${USER_ID}:${GROUP_ID}
    ports:
      - 8000:8000
    volumes:
      - ./src:/app
      # Set the logins and groups identical to host environment
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro